### ISSUE TITLE
Support for connecttech GMSL serdeser board?

### ISSUE THREAD

**Issue by dongx3** [FLIR/Xavier_Heater_Test#1]
Hello,

I'm using xavier with GMSL serdeser board from connecttech
(http://connecttech.com/product/xavier-gmsl-camera-platform/)

Is it possible to use ADK with this?
It seems board support comes with binary form.

**Comment by ethanfrantz** [comment]
We do not support the Connected Tech board at the moment. There is no current plan to support it in the future. We recommend the D3 engineering board. https://store.d3engineering.com/product/designcore-nvidia-jetson-serdes-card/
